version: "3.9"

services:
  app:
    container_name: app
    build: .
    ports:
      - 8000:8000
    restart: always
    environment:
      DB_CONNECTION: "mysql+mysqlconnector://db_user:db_password@db_domain:3306/common"
    links:
      - db:db_domain
    depends_on:
      - db

  db:
    container_name: mariadb
    image: mariadb:10.5
    volumes:
      - dbvolume:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: common
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: db_password

volumes:
  dbvolume: