"""init

Revision ID: 5725c4b2f5e2
Revises: 
Create Date: 2021-03-14 04:46:50.580362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5725c4b2f5e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('courier_type', sa.Enum('foot', 'bike', 'car', name='courier_type'), nullable=False),
    sa.PrimaryKeyConstraint('courier_id', name=op.f('pk__couriers'))
    )
    op.create_table('regions',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('region_id', name=op.f('pk__regions'))
    )
    op.create_table('courier_to_region',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.courier_id'], name=op.f('fk__courier_to_region__courier_id__couriers')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name=op.f('fk__courier_to_region__region_id__regions')),
    sa.PrimaryKeyConstraint('courier_id', 'region_id', name=op.f('pk__courier_to_region'))
    )
    op.create_table('orders_assign',
    sa.Column('assign_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('assign_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.courier_id'], name=op.f('fk__orders_assign__courier_id__couriers')),
    sa.PrimaryKeyConstraint('assign_id', name=op.f('pk__orders_assign'))
    )
    op.create_table('working_bands',
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=20), nullable=False),
    sa.Column('end', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.courier_id'], name=op.f('fk__working_bands__courier_id__couriers')),
    sa.PrimaryKeyConstraint('band_id', name=op.f('pk__working_bands'))
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('complete_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('assign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assign_id'], ['orders_assign.assign_id'], name=op.f('fk__orders__assign_id__orders_assign')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name=op.f('fk__orders__region_id__regions')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk__orders'))
    )
    op.create_table('delivery_bands',
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=20), nullable=False),
    sa.Column('end', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk__delivery_bands__order_id__orders')),
    sa.PrimaryKeyConstraint('band_id', name=op.f('pk__delivery_bands'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_bands')
    op.drop_table('orders')
    op.drop_table('working_bands')
    op.drop_table('orders_assign')
    op.drop_table('courier_to_region')
    op.drop_table('regions')
    op.drop_table('couriers')
    # ### end Alembic commands ###
