name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Python Linting
        uses: WhyNotHugo/python-linting@v1.0.0

      - name: Run tests
        run: pytest
